site_name: Rivers Blog

copyright: "<a href='http://www.miitbeian.gov.cn'target='_blank'>京ICP备19046279号-1</a>"


nav:
  - 首页: 
    - index.md

  - 产品汪:
    - PM笔记:
      - 高级PM笔记:
        - PM/PM笔记/P3notes/P3课程笔记1.md
        - PM/PM笔记/P3notes/P3课程笔记2.md
        - PM/PM笔记/P3notes/P3课程笔记3.md
        - PM/PM笔记/P3notes/P3课程笔记4.md
        - PM/PM笔记/P3notes/P3课程笔记5.md
        - PM/PM笔记/P3notes/P3课程笔记6.md
        - PM/PM笔记/P3notes/P3课程笔记7.md
      - 中台PM笔记:
        - PM/PM笔记/中台/中台PM笔记1.md
        - PM/PM笔记/中台/中台PM笔记2.md
        - PM/PM笔记/中台/中台PM笔记3.md
        - PM/PM笔记/中台/中台PM笔记4.md
        - PM/PM笔记/中台/中台PM笔记5.md
        - PM/PM笔记/中台/中台PM笔记6.md
        - PM/PM笔记/中台/中台PM笔记7.md
        - PM/PM笔记/中台/中台PM笔记8.md

      - 工具型产品:
        - PM/PM笔记/工具型产品/工具型产品的一些思考.md

    - 项目合集:
      - PM/项目集/阳光筹.md
      - PM/项目集/RupiahOne官网.md
      - PM/项目集/SaaS产品需求概要.md
      - PM/项目集/觅影.md

  - AI技术: 
    - 自然语言处理:
      - AI/NLP/自然语言处理简介.md
      - AI/NLP/自然语言处理应用.md
    - 机器学习:
      - AI/ML/统计学习及监督学习概论.md

    - Kaggle:
      - AI/Kaggle/Kaggle学习笔记.md
  - Mac生产力工具: 
    - iTerm2: MacTools/iTerm2简明使用教程.md

    - Typora: MacTools/Typora简明使用教程.md
    - 常用Git命令: MacTools/Git常用命令清单.md
  - 作者: 
    - 关于作者: about.md

theme: 
  name: material
  language: 'zh'
  palette:
    primary: 'Deep Purple'
    accent: 'Deep Purple'
  feature:
    tabs: true

markdown_extensions:
  - markdown.extensions.attr_list
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - mdx_math
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra:
  search:
    language: 'jp'




extra_javascript:
  - 'js/extra.js'
  - 'js/baidu-tongji.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js
  - js/umlconvert.js

extra_css:
  - 'css/extra.css'
