# Project information
site_name: Rivers Blog
site_description: 'Rivers Blog'
site_url: https://riversblog.site/
base_url: https://riversblog.site/

# Repository
repo_name: 'Rivers19/Blog'
repo_url: 'https://github.com/Rivers19/Blog'

# Copyright
copyright: "<a href='http://www.miitbeian.gov.cn'target='_blank'>京ICP备19046279号-1</a>"

# Configuration
theme:
  name: 'material'
  language: 'zh'
  palette:
      #primary: 'white'
    primary: 'Deep Purple'
    accent: 'Deep Purple'
  feature:
    tabs: true

extra:
  social:
    - type: 'github'
      link: 'https://github.com/Rivers19'
      #  disqus: 'Rivers19'

# Extensions
markdown_extensions:
  - markdown.extensions.attr_list
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - mdx_math
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra:
  search:
    language: 'jp'




extra_javascript:
  - 'js/extra.js'
  - 'js/baidu-tongji.js'
  - 'js/umlconvert.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js
extra_css:
  - 'css/extra.css'

# Sturcture of Docs
nav:
  - 首页: 
    - index.md

  - 产品汪:
    - PM笔记:
      - 产品方法论:
        - PM/PM笔记/俞军产品方法论/产品经理做什么.md
        - PM/PM笔记/俞军产品方法论/关于企业用户产品.md
        - PM/PM笔记/俞军产品方法论/交易.md
      - 高级PM笔记:
        - PM/PM笔记/P3notes/P3课程笔记1.md
        - PM/PM笔记/P3notes/P3课程笔记2.md
        - PM/PM笔记/P3notes/P3课程笔记3.md
        - PM/PM笔记/P3notes/P3课程笔记4.md
        - PM/PM笔记/P3notes/P3课程笔记5.md
        - PM/PM笔记/P3notes/P3课程笔记6.md
        - PM/PM笔记/P3notes/P3课程笔记7.md
      - 中台PM笔记:
        - PM/PM笔记/中台/中台PM笔记1.md
        - PM/PM笔记/中台/中台PM笔记2.md
        - PM/PM笔记/中台/中台PM笔记3.md
        - PM/PM笔记/中台/中台PM笔记4.md
        - PM/PM笔记/中台/中台PM笔记5.md
        - PM/PM笔记/中台/中台PM笔记6.md
        - PM/PM笔记/中台/中台PM笔记7.md
        - PM/PM笔记/中台/中台PM笔记8.md
      - 工具型产品:
        - PM/PM笔记/工具型产品/工具型产品的一些思考.md
      - 杂文:
        - PM/PM笔记/杂文/张小龙关于信息互联的七点思考.md
 


    - 项目合集:
      - PM/项目集/阳光筹.md
      - PM/项目集/RupiahOne官网.md
      - PM/项目集/RupiahOne项目总结.md
      - PM/项目集/SaaS产品需求概要.md
      - PM/项目集/China.cn会员后台.md
      - PM/项目集/China.cn运营管理平台.md
      - PM/项目集/觅影.md
  - 技术:
    - AI: 
      - 自然语言处理:
        - Tech/AI/NLP/自然语言处理简介.md
        - Tech/AI/NLP/自然语言处理应用.md
      - 机器学习:
        - Tech/AI/ML/统计学习及监督学习概论.md
      - 语音:
        - Tech/AI/Speech/语音交互基础.md
    - DataMining:
      - Kaggle:
        - Tech/DataMining/Kaggle/数据基础.md
        - Tech/DataMining/Kaggle/数据描述.md
        - Tech/DataMining/Kaggle/Kaggle学习笔记.md
       
      - SQL:
        - Tech/DataMining/SQL/SQL学习笔记.md
    - Basic:
      - Linux:
        - Tech/Basic/Linux基础.md
        - Tech/Basic/正则表达式.md
  - 生产力工具: 
    - iTerm2: MacTools/iTerm2简明使用教程.md
    - Typora: MacTools/Typora简明使用教程.md
    - 常用Git命令: MacTools/Git常用命令清单.md
    - GitHub搜索技巧: MacTools/GitHub搜索技巧.md
  - 作者: 
    - 关于作者: about.md